### ISSUE TITLE
Wonky scroll bar

### ISSUE THREAD

**Issue by AlekseyPanas** [1whatleytay/saturn#10]
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/47086586/229384831-2f58a820-7328-4e0e-a29d-fd6f8e878476.png">

When you open enough files, a jarring scroll bar appears at the top. A little wonky, Id hide the scroll bar
(This was on mac btw)

**Comment by 1whatleytay** [comment]
(Hopefully) resolved.
