### ISSUE TITLE
Undo performing wrong change

### ISSUE THREAD

**Issue by AlekseyPanas** [1whatleytay/saturn#11]
This is a very obscure bug. I've been working for many hours over the course of multiple days without restarting the program. 

I pressed undo and for some reason it removed some earlier change instead a recent one. This has never happened before and restarting the program fixed the issue. 

I don't have a consistent replication procedure, but maybe the data structure that you use to store the sequence of changes filled up (if thats even possible)?

**Comment by 1whatleytay** [comment]
Should be resolved in 0.1.6. Re-open if something goes wrong!
