### ISSUE TITLE
sgtu not working properly

### ISSUE THREAD

**Issue by AlekseyPanas** [1whatleytay/saturn#12]
I discovered that `sgtu` and `sltu` do the same thing.

<img width="638" alt="image" src="https://user-images.githubusercontent.com/47086586/229605481-79e24674-7d5e-415c-b90d-a0b772a2877e.png">

In the image you see the register states after running those 6 lines. t2 should be 1 since t1 is greater than t0. Unless Im missing something, I think this is a bug

**Comment by 1whatleytay** [comment]
That's embarrassing. Pushed a fix for this in 0.1.6 (sgt/sgtu).

**Comment by 1whatleytay** [comment]
Closing with #11 and #10. Reopen if this is not fixed yet.
