### ISSUE TITLE
Allow for .word directive to store the address of a label

### ISSUE THREAD

**Issue by MrSunshineVS** [1whatleytay/saturn#3]
Hello! I've been using Saturn for my Csc258 project this semester and it's AMAZING. Thank you for freeing us from MARS hell.
I'm trying to use virtual lookup tables for functions, and also state logic, things that would require me to store a pointer to a function. I believe this is not currently supported. The syntax of a possible implementation may look something like this:

![Screenshot 2023-03-22 045751](https://user-images.githubusercontent.com/24392379/226851541-f185b716-b818-427b-b596-9a16b1e967ba.png)

I believe this would be useful for many other OOP purposes.
Thanks again for this awesome software!!

**Comment by 1whatleytay** [comment]
Hey! I just saw this right about now- thanks for filing this! This is totally doable with the currently assembler setup. I've gone ahead and implemented this 0.1.5 latest. 
<img width="801" alt="Screenshot 2023-03-23 at 9 16 57 PM" src="https://user-images.githubusercontent.com/32211852/227399788-1e71c6c9-f5a3-4132-8e76-519f46bdeb01.png">

When you have a chance, can you redownload the latest build here and give it a try https://github.com/1whatleytay/saturn/releases/tag/app-v0.1.5?

**Comment by MrSunshineVS** [comment]
Works perfectly, been using it for 2 days with no issues :) thank you so much!

**Comment by 1whatleytay** [comment]
Closing with the release of v0.1.5
