### ISSUE TITLE
Not Recognizing Characters

### ISSUE THREAD

**Issue by AlekseyPanas** [1whatleytay/saturn#7]
Defining a newline string like so 
<img width="319" alt="image" src="https://user-images.githubusercontent.com/47086586/228960596-1c9523a6-7ead-4a30-a03d-5f2251d9cf8b.png">
and the printing it using the string syscall
<img width="133" alt="image" src="https://user-images.githubusercontent.com/47086586/228960700-7cf83bbb-b8ff-401d-b6a9-4e24a8f87f87.png">
results in this:
<img width="462" alt="image" src="https://user-images.githubusercontent.com/47086586/228960786-9586f240-63cc-4873-9fbf-883fb92c2798.png">

if you put the ascii values instead
<img width="279" alt="image" src="https://user-images.githubusercontent.com/47086586/228960900-e7767c11-0269-4655-bf3f-022865d11546.png">
then it works fine. It seems like Saturn doesn't automatically recognize characters

**Comment by 1whatleytay** [comment]
Woah! Yep `\0` isn't considered a break character and instead gets encoded as an actual 0 for some reason.

**Comment by 1whatleytay** [comment]
Added a null terminator escape sequence in 0.1.6. After the build finishes in around ~20 you should be able to pull https://github.com/1whatleytay/saturn/releases/tag/app-v0.1.6 and this code should work. As for character literals though, I recommend using `.asciiz`!

<img width="582" alt="Screenshot 2023-03-31 at 12 04 08 PM" src="https://user-images.githubusercontent.com/32211852/229172148-acd9748d-e30e-4cb7-9d28-92cb3c3f2e37.png">

**Comment by 1whatleytay** [comment]
Closing for the time being (until this feature rebels and decides to not work again).
