### ISSUE TITLE
Memory Offset Returning to Default on Switch

### ISSUE THREAD

**Issue by AlekseyPanas** [1whatleytay/saturn#8]
When you set a custom address to search for in memory, Saturn doesn't remember it. That is, if you switch to the registers tab and then back again, it will reset to default. This makes it difficult to monitor a particular area of memory and the registers at the same time

**Comment by 1whatleytay** [comment]
Yep! Totally on board with this one. Memory tab was written really early into Saturn's lifetime (when I was trying to debug why the interpreter wasn't working) and still has lots of quirks. It's due for a rewrite.

**Comment by 1whatleytay** [comment]
This was made a Setting internally. This should be remembered now after you leave the tab in 0.1.7 👍
